on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: geovanams/actionteste@v1.1.1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
